### ISSUE TITLE
maybe change default config path?

### ISSUE THREAD

**Issue by cj360** [nan0s7/nfancurve#17]
This may just be an issue from the aur not this script, so if this should be on the aur's page not here let me know.

In this script's case since the install dir is the default config location, it seems bad that its looking for a config among `/usr/bin`. On the other hand, it seems weird to ask the person that made the aur package to change the original script. Just a nitpick really not actually a problem if I just cloned the repo.

**Comment by nan0s7** [comment]
Yeah this can't _really_ be helped unless the default path is forced to be somewhere in the users home directory. It does suit that the default config location is the install location because the main script has no sense of what the default values should be. 

But of course that is why there's an option to run the script with a config path command line option.

**Comment by ReneHollander** [comment]
In the new AUR package the config is located in /etc/nfancurve.conf. The provided systemd user unit will use that config.

Just beware, enabling the nfancurve.service does not start it at boot. I am still trying to get it to work, but running `systemd --user start nfancurve.service` works fine.
