### ISSUE TITLE
What a mess

### ISSUE THREAD

**Issue by HanM23** [nan0s7/nfancurve#45]
what is NFANCURVE_PATH
what is update.sh ???

Your thing is such a mess man

**Comment by nan0s7** [comment]
You're right.
My deepest apologies.
I have since removed the two bits of text that you graciously alerted me to their locations and uselessness, as they were remains of a previous version.
I really do hope these two bits of meaningless text did not stop the script from working for you, and that you were able to figure out how to use it regardless.
Please keep me informed if you find any further issues that prevent things from working on your system.
Thank you for your help.
