### ISSUE TITLE
Error: Integer expected

### ISSUE THREAD

**Issue by infomanPMF** [nan0s7/nfancurve#6]
./temp.sh: line 286: [: : integer expression expected

###################################
# nan0s7's fan speed curve script #
###################################

No other versions of temp.sh running in background
A likely supported driver version was detected
Configuration loaded
Number of Fans detected: 
Number of GPUs detected: 
1
tdiff average: 12

./temp.sh: line 286: [: : integer expression expected
Submit an issue on my GitHub page... happy to fix this :D

1 GPU on gjorge-G752VT:0

    [0] gjorge-G752VT:0[gpu:0] (GeForce GTX 970M)

      Has the following names:
        GPU-0
        GPU-3f936eaa-d22c-99e2-d84f-87d2ee9dc576

Fan control set back to auto mode

**Comment by nan0s7** [comment]
Interesting, it seems it didn't detect any fans on your GPU. Can you paste the output of this command here? `nvidia-settings -q fans` Thank you!

**Comment by infomanPMF** [comment]
That's definitely it. When i ran the command it returned an empty row.

**Comment by infomanPMF** [comment]
I have Asus Rog G752VT,
It has 2 fans for CPU and GPU. My brother has an older version of the laptop and your code is working fine for him. I guess mine is not that supported by linux.

**Comment by infomanPMF** [comment]
Sorry for bugging you at all, I don't usually do this but nothing seems to work for my laptop and its coolers are always working on max because of it. 

Kernel: 
Linux gjorge-G752VT 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

NVIDIA Driver Version: 
384.130

Thanks for trying to help.

**Comment by nan0s7** [comment]
No problem, I'm more than happy to help. I remember having a similar issue with my super old laptop; the fans would always be running at 100% - turned out to be an outdated kernel issue.

The latest kernel is 4.18.14 and the latest NVIDIA driver is 410.57-6. Although upgrading the NVIDIA driver likely won't help with fan detection (more just performance/efficiency), upgrading the kernel may help. It should be relatively easy on Ubuntu. 

Here are the latest kernel builds for Ubuntu: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.18.14/

Under the heading "Build for amd64 succeeded" you'll need all the files (should be 3) that have "generic" in the title of them, and you'll need the one that ends in "all.deb" for a total of 4 files (should be the first file under the amd64 heading). A quick Google should tell you what commands you need to use, but from memory you should just be able to put those 4 files in a folder, `cd` to that folder in a terminal, and run `dpkg -i *.deb` with `sudo`.

Let me know if that helps the fans; if that slows them down we should be able to get my script working with them from there.

**Comment by nan0s7** [comment]
Was this issue solved by the update? Let me know, otherwise I'll be closing this issue in a months time. :)

**Comment by infomanPMF** [comment]
Wasn't able to resolve it and frankly I gave up on trying to fix it. I'll close the issue

**Comment by nan0s7** [comment]
> Wasn't able to resolve it and frankly I gave up on trying to fix it. I'll close the issue

Sorry to hear that. Happy to help with any future problems you may have :)
